image: node:10.16.3

cache:
    paths:
        - node_modules

stages:
    - test

run_test:
    stage: test
    script:
        - yarn install --frozen-lockfile --silent --non-interactive
        - yarn test
    tags:
        - node

run_lint:
    stage: test
    script:
        - yarn install --frozen-lockfile --silent --non-interactive
        - yarn run lint
    tags:
        - node
